# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update scripts on Angrezi Server

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.environment/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.environment/**'

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Deploy Scripts
        uses: azohra/shell-linter@latest
        with:
          path: ".environment"
  
      - name: Update scripts on Angrezi Server
        run: sudo /opt/services/run-deploy.sh ${{ github.event.repository.name }}
